name: Quality Check & Build

on:
  push:
    branches:
      - '**'

permissions:
  checks: write
  contents: write

jobs:
  setup:
    name: Setup Environment
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.cache.outputs.cache-hit }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: .bun
          key: ${{ runner.os }}-bun-${{ hashFiles('bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install --ci

  quality:
    name: Code Quality Check
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: Run Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest

      - name: Lint and Format Check
        run: biome ci .

  build:
    name: Build Project
    runs-on: ubuntu-latest
    needs: [quality]
    steps:
      - name: Build
        run: bun run build

  outdated-dependencies:
    name: Check for Outdated Dependencies
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: Check Outdated Dependencies
        run: bun upgrade --dry-run
