name: Quality Check, Build & Release

on:
  push:
    branches:
      - '**'

permissions:
  checks: write
  contents: write

jobs:
  setup:
    name: Setup Environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21
          check-latest: true

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --ci

  quality:
    name: Code Quality Check
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: Run Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest

      - name: Lint and Format Check
        run: biome ci .

  build:
    name: Build Project
    runs-on: ubuntu-latest
    needs: [quality]
    steps:
      - name: Build
        run: bun run build

  outdated-dependencies:
    name: Check for Outdated Dependencies
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: Check Outdated Dependencies
        run: bun upgrade --dry-run

  release:
    name: Semantic Release
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref == 'refs/heads/main' # Ensure it only runs on main branch
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21
          check-latest: true

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --ci

      - name: Run Semantic Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: bunx semantic-release
